create table Country (
    id int auto_increment primary key,
    continentId int not null,
    name varchar(255) not null,
    isoCode varchar(255) null,
    constraint Country_ibfk_1 foreign key (continentId) references Continent (id)
);

create index continentId on Country (continentId);

INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (1, 1, 'Afghanistan', 'AFG');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (2, 2, 'Albania', 'ALB');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (3, 5, 'Algeria', 'DZA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (4, 6, 'American Samoa', 'ASM');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (5, 2, 'Andorra', 'AND');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (6, 5, 'Angola', 'AGO');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (7, 4, 'Antigua and Barbuda', 'ATG');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (8, 3, 'Argentina', 'ARG');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (9, 1, 'Armenia', 'ARM');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (10, 6, 'Australia', 'AUS');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (11, 2, 'Austria', 'AUT');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (12, 1, 'Azerbaijan', 'AZE');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (13, 1, 'Bahamas', 'BHS');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (14, 1, 'Bahrain', 'BHR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (15, 1, 'Bangladesh', 'BGD');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (16, 4, 'Barbados', 'BRB');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (17, 2, 'Belarus', 'BLR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (18, 2, 'Belgium', 'BEL');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (19, 4, 'Belize', 'BLZ');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (20, 5, 'Benin', 'BEN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (21, 4, 'Bermuda', 'BMU');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (22, 1, 'Bhutan', 'BTN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (23, 3, 'Bolivia', 'BOL');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (24, 2, 'Bosnia and Herzegovina', 'BIH');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (25, 5, 'Botswana', 'BWA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (26, 3, 'Brazil', 'BRA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (27, 5, 'Brunei', 'BRN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (28, 2, 'Bulgaria', 'BGR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (29, 5, 'Burkina Faso', 'BFA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (30, 5, 'Burundi', 'BDI');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (31, 1, 'Cambodia', 'KHM');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (32, 5, 'Cameroon', 'CMR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (33, 4, 'Canada', 'CAN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (34, 5, 'Cape Verde', 'CPV');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (35, 5, 'Central African Republic', 'CAF');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (36, 5, 'Chad', 'TCD');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (37, 3, 'Chile', 'CHL');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (38, 1, 'China', 'CHN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (39, 3, 'Colombia', 'COL');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (40, 5, 'Comoros', 'COM');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (41, 5, 'Congo', 'COG');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (42, 6, 'Cook Islands', 'COK');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (43, 4, 'Costa Rica', 'CRI');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (44, 5, 'Cote d\'Ivoire', 'CIV');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (45, 2, 'Croatia', 'HRV');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (46, 4, 'Cuba', 'CUB');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (47, 2, 'Cyprus', 'CYP');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (48, 2, 'Czechia', 'CZE');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (49, 5, 'Democratic Republic of Congo', 'COD');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (50, 2, 'Denmark', 'DNK');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (51, 5, 'Djibouti', 'DJI');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (52, 4, 'Dominica', 'DMA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (53, 4, 'Dominican Republic', 'DOM');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (54, 3, 'Ecuador', 'ECU');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (55, 5, 'Egypt', 'EGY');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (56, 4, 'El Salvador', 'SLV');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (57, 5, 'Equatorial Guinea', 'GNQ');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (58, 5, 'Eritrea', 'ERI');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (59, 2, 'Estonia', 'EST');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (60, 5, 'Eswatini', 'SWZ');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (61, 5, 'Ethiopia', 'ETH');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (62, 6, 'Fiji', 'FJI');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (63, 2, 'Finland', 'FIN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (64, 2, 'France', 'FRA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (65, 5, 'Gabon', 'GAB');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (66, 5, 'Gambia', 'GMB');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (67, 1, 'Georgia', 'GEO');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (68, 2, 'Germany', 'DEU');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (69, 5, 'Ghana', 'GHA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (70, 2, 'Greece', 'GRC');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (71, 2, 'Greenland', 'GRL');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (72, 3, 'Grenada', 'GRD');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (73, 3, 'Guam', 'GUM');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (74, 3, 'Guatemala', 'GTM');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (75, 5, 'Guinea', 'GIN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (76, 5, 'Guinea-Bissau', 'GNB');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (77, 3, 'Guyana', 'GUY');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (78, 4, 'Haiti', 'HTI');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (79, 4, 'Honduras', 'HND');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (80, 2, 'Hungary', 'HUN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (81, 2, 'Iceland', 'ISL');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (82, 1, 'India', 'IND');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (83, 1, 'Indonesia', 'IDN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (84, 1, 'Iran', 'IRN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (85, 1, 'Iraq', 'IRQ');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (86, 2, 'Ireland', 'IRL');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (87, 1, 'Israel', 'ISR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (88, 2, 'Italy', 'ITA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (89, 5, 'Jamaica', 'JAM');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (90, 1, 'Japan', 'JPN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (91, 1, 'Jordan', 'JOR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (92, 1, 'Kazakhstan', 'KAZ');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (93, 5, 'Kenya', 'KEN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (94, 5, 'Kiribati', 'KIR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (95, 1, 'Kuwait', 'KWT');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (96, 1, 'Kyrgyzstan', 'KGZ');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (97, 1, 'Laos', 'LAO');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (98, 2, 'Latvia', 'LVA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (99, 1, 'Lebanon', 'LBN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (100, 5, 'Lesotho', 'LSO');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (101, 5, 'Liberia', 'LBR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (102, 5, 'Libya', 'LBY');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (103, 2, 'Lithuania', 'LTU');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (104, 2, 'Luxembourg', 'LUX');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (105, 5, 'Madagascar', 'MDG');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (106, 6, 'Malawi', 'MWI');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (107, 1, 'Malaysia', 'MYS');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (108, 6, 'Maldives', 'MDV');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (109, 5, 'Mali', 'MLI');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (110, 2, 'Malta', 'MLT');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (111, 6, 'Marshall Islands', 'MHL');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (112, 6, 'Mauritania', 'MRT');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (113, 6, 'Mauritius', 'MUS');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (114, 4, 'Mexico', 'MEX');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (115, 6, 'Micronesia ', 'FSM');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (116, 2, 'Moldova', 'MDA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (117, 2, 'Monaco', 'MCO');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (118, 1, 'Mongolia', 'MNG');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (119, 2, 'Montenegro', 'MNE');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (120, 1, 'Morocco', 'MAR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (121, 5, 'Mozambique', 'MOZ');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (122, 1, 'Myanmar', 'MMR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (123, 5, 'Namibia', 'NAM');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (124, 6, 'Nauru', 'NRU');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (125, 1, 'Nepal', 'NPL');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (126, 2, 'Netherlands', 'NLD');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (127, 6, 'New Zealand', 'NZL');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (128, 5, 'Nicaragua', 'NIC');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (129, 5, 'Niger', 'NER');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (130, 5, 'Nigeria', 'NGA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (131, 6, 'Niue', 'NIU');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (132, 1, 'North Korea', 'PRK');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (133, 2, 'North Macedonia', 'MKD');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (134, 6, 'Northern Mariana Islands', 'MNP');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (135, 2, 'Norway', 'NOR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (136, 1, 'Oman', 'OMN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (137, 1, 'Pakistan', 'PAK');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (138, 6, 'Palau', 'PLW');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (139, 1, 'Palestine', 'PSE');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (140, 4, 'Panama', 'PAN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (141, 6, 'Papua New Guinea', 'PNG');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (142, 3, 'Paraguay', 'PRY');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (143, 3, 'Peru', 'PER');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (144, 1, 'Philippines', 'PHL');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (145, 2, 'Poland', 'POL');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (146, 2, 'Portugal', 'PRT');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (147, 4, 'Puerto Rico', 'PRI');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (148, 1, 'Qatar', 'QAT');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (149, 2, 'Romania', 'ROU');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (150, 2, 'Russia', 'RUS');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (151, 5, 'Rwanda', 'RWA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (152, 4, 'Saint Kitts and Nevis', 'KNA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (153, 4, 'Saint Lucia', 'LCA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (154, 4, 'Saint Vincent and the Grenadines', 'VCT');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (155, 6, 'Samoa', 'WSM');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (156, 2, 'San Marino', 'SMR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (157, 4, 'Sao Tome and Principe', 'STP');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (158, 1, 'Saudi Arabia', 'SAU');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (159, 5, 'Senegal', 'SEN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (160, 2, 'Serbia', 'SRB');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (161, 1, 'Seychelles', 'SYC');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (162, 1, 'Sierra Leone', 'SLE');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (163, 1, 'Singapore', 'SGP');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (164, 2, 'Slovakia', 'SVK');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (165, 2, 'Slovenia', 'SVN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (166, 6, 'Solomon Islands', 'SLB');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (167, 5, 'Somalia', 'SOM');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (168, 5, 'South Africa', 'ZAF');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (169, 1, 'South Korea', 'KOR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (170, 5, 'South Sudan', 'SSD');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (171, 2, 'Spain', 'ESP');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (172, 1, 'Sri Lanka', 'LKA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (173, 1, 'Sudan', 'SDN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (174, 5, 'Suriname', 'SUR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (175, 2, 'Sweden', 'SWE');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (176, 2, 'Switzerland', 'CHE');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (177, 5, 'Syria', 'SYR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (178, 1, 'Taiwan', 'TWN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (179, 1, 'Tajikistan', 'TJK');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (180, 5, 'Tanzania', 'TZA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (181, 1, 'Thailand', 'THA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (182, 5, 'Timor', 'TLS');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (183, 5, 'Togo', 'TGO');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (184, 6, 'Tokelau', 'TKL');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (185, 5, 'Tonga', 'TON');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (186, 4, 'Trinidad and Tobago', 'TTO');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (187, 5, 'Tunisia', 'TUN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (188, 2, 'Turkey', 'TUR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (189, 1, 'Turkmenistan', 'TKM');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (190, 6, 'Tuvalu', 'TUV');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (191, 5, 'Uganda', 'UGA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (192, 2, 'Ukraine', 'UKR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (193, 1, 'United Arab Emirates', 'ARE');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (194, 2, 'United Kingdom', 'GBR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (195, 4, 'United States', 'USA');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (196, 6, 'United States Virgin Islands', 'VIR');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (197, 3, 'Uruguay', 'URY');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (198, 1, 'Uzbekistan', 'UZB');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (199, 6, 'Vanuatu', 'VUT');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (200, 3, 'Venezuela', 'VEN');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (201, 1, 'Vietnam', 'VNM');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (202, 1, 'Yemen', 'YEM');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (203, 5, 'Zambia', 'ZMB');
INSERT INTO `test-db`.Country (id, continentId, name, isoCode) VALUES (204, 5, 'Zimbabwe', 'ZWE');
