CREATE TRIGGER year_check_insert BEFORE INSERT ON Year
FOR EACH ROW
BEGIN
  IF NEW.value < 1900 THEN
    SET NEW.value = 1900;
  ELSEIF NEW.value > 2100 THEN
    SET NEW.value = 2100;
  END IF;
END;

CREATE TRIGGER year_check_update BEFORE UPDATE ON Year
FOR EACH ROW
BEGIN
  IF NEW.value < 1900 THEN
    SET NEW.value = 1900;
  ELSEIF NEW.value > 2100 THEN
    SET NEW.value = 2100;
  END IF;
END;/